import React from 'react'
import './scripts.js'
import './styles.css'


export default function FAQ() {
  return (
    <div id='faq'>
      <div class="container p-5 ">
      <div class="col-md-12 text-center ">

<div class="photo-section-heading absolute-center max-width  " style={{color:'white'}}>FAQ</div>

{/* <div class="photo-section-subheading">There are many variations of passages of Lorem Ipsum available but the \n majority have suffered alteration in some injected humour</div> */}

</div> 
      <div class="accordion" id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingOne">
      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
      Who is your targeted customers?
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>We'll be primarily selling our product to luxury goods manufacturers as we look at ourselves like a B2B company.</strong> Here, NFC tags would be the end tangible product that would be sold to these manufacturers, which has to be embedded into their product. This NFC tag would contain details like model number, date of manufacturing etc. The mobile app would be used to validate the tag. We're keeping the app free-to-use on Play Store. Our main revenue would be generated by selling NFC Tags in bulk to these manufacturers.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
      What we do?
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>We at Authscate aim to solve the authentication issue using blockchain and NFC technology</strong> Going by the principles, data fed into a blockchain cannot be edited by a third entity and hence is permanent in nature. We aim to use this to our advantage and provide a reliable authentication and warranty solution to luxury retailers all across the country.
      </div>
    </div>
  </div>
  {/*<div class="accordion-item">
    <h2 class="accordion-header" id="headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Accordion Item #3
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
        <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div>*/}
</div>
</div>
</div>
  )}
